server:
  port: 8090
  servlet:
    context-path: /informational-dxn/v1/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/informational_dxn?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    generate-ddl: true
    # org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

  #  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    timeout: 1000ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  transaction:
    rollback-on-commit-failure: true
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
jwtparam:
  issuer: ec8b63c05f999a15a8c8567002a560a8
  audience: 541bee7d2a922cc0a81ff4ca3c23f4af
  TTLMillis: 3600000
  base64Security: JXU4RDM1JXU3MTY0JXU4QkJFJXU4QkEx1

file.path: E:&&file
# 图片类型判断
image.format: jpg;JPG;bmp;BMP;png;PNG

logging:
  level:
      org.hibernate.type.descriptor.sql.BasicBinder: trace



system:
  config:
    # 煤矿平台的默认密码
    cm-platform-default-password: 123456
